import json
import re
import sys
import os

def parse_branch_logs(file_path):
    """
    Parses the branchlogs.txt file and extracts request/response pairs.
    """
    if not os.path.exists(file_path):
        print(f"Error: Log file not found at {file_path}")
        return []

    with open(file_path, 'r') as f:
        content = f.read()

    # Pattern to match the log blocks generated by IBranchRequestTracingCallback
    # Format: 
    # URI Sent to Branch: <uri>
    # Request: <json>
    # Response: <json>
    # Error Message: <msg>
    # Request Url: <url>
    
    entries = []
    # Split by the start of a log block
    blocks = re.split(r'URI Sent to Branch: ', content)
    
    for block in blocks:
        if not block.strip():
            continue
            
        entry = {}
        lines = block.split('\n')
        entry['uri'] = lines[0].strip()
        
        # Extract Request JSON
        req_match = re.search(r'Request: (\{.*\})', block)
        if req_match:
            try:
                entry['request'] = json.loads(req_match.group(1))
            except json.JSONDecodeError:
                entry['request_raw'] = req_match.group(1)

        # Extract Response JSON
        res_match = re.search(r'Response: (\{.*\})', block)
        if res_match:
            try:
                entry['response'] = json.loads(res_match.group(1))
            except json.JSONDecodeError:
                entry['response_raw'] = res_match.group(1)
        
        if 'request' in entry:
            entries.append(entry)
            
    return entries

def validate_entries(entries):
    """
    Performs assertions on the captured entries.
    """
    errors = []
    
    if not entries:
        errors.append("No Branch SDK requests were captured in the logs.")
        return errors

    # Check for mandatory events in the capture session
    found_uris = [e.get('uri') for e in entries]
    mandatory_events = ['/v1/install'] # Or /v1/open depending on the test
    for me in mandatory_events:
        if me not in found_uris:
            errors.append(f"Mandatory event '{me}' was not captured during the session.")

    print(f"Captured {len(entries)} Branch requests. Starting validation...")

    for i, entry in enumerate(entries):
        uri = entry.get('uri')
        req = entry.get('request', {})
        
        print(f"[{i+1}] Validating {uri}...")
        
        # Common required fields for all Branch requests
        required_base = ['sdk', 'device_fingerprint_id', 'branch_key']
        for field in required_base:
            if field not in req:
                errors.append(f"Request {i+1} ({uri}): Missing required field '{field}'")

        # Specific validation based on URI
        if uri == '/v1/install':
            if 'hardware_id' not in req:
                errors.append(f"Request {i+1} (/v1/install): Missing 'hardware_id'")
        
        if uri == '/v1/open':
            if 'device_fingerprint_id' not in req:
                errors.append(f"Request {i+1} (/v1/open): Missing 'device_fingerprint_id'")

    return errors

if __name__ == "__main__":
    # In a CI environment, the log file would be pulled from the device via adb
    log_file_path = sys.argv[1] if len(sys.argv) > 1 else "branchlogs.txt"
    
    found_entries = parse_branch_logs(log_file_path)
    validation_errors = validate_entries(found_entries)
    
    if validation_errors:
        print("\n--- VALIDATION FAILED ---")
        for err in validation_errors:
            print(f"FAILED: {err}")
        sys.exit(1)
    else:
        print("\n--- VALIDATION PASSED ---")
        sys.exit(0)
